version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: 
          aws-access-key-id: \"$AWS_ACCESS_KEY_ID\"
          aws-secret-access-key: \"$AWS_ECR_ACCOUNT_URL\"
          create-repo: false
          dockerfile: Dockerfile
          path: .
          region: \"ap-south-1\"
          repo: circleci-ecr-orb-demo
          tag: "$CIRCLE_SHA1"
