version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@0.0.4

workflows:
  build_test_deploy:
    jobs:
      - build_test
    
      - aws-ecr/build_and_push_image:
          region: ap-south-1
          account-url: ${AWS_ECR_ACCOUNT_URL}
          repo: circleci-ecr-orb-demo
          tag: ${CIRCLE_BUILD_NUM}
          requires:
            - build_test
jobs:
  build_test:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Setup VirtualEnv
          command: |
          
            make
