version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: 132265928525.dkr.ecr.ap-south-1.amazonaws.com
          aws-access-key-id: AKIAR5S5J45GQ6FGBM2N
          aws-secret-access-key: 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
          create-repo: false
          dockerfile: Dockerfile
          path: .
          region: "ap-south-1"
          repo: circleci-ecr-orb-demo
          tag: "$CIRCLE_SHA1"
