version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@0.0.4

workflows:
  build_test_deploy:
    jobs:
      - build_test
    
      - aws-ecr/build_and_push_image:
          region: ap-south-1
          account-url: ${AWS_ECR_ACCOUNT_URL}
          repo: ${CIRCLE_PROJECT_REPONAME}
          tag: ${CIRCLE_BUILD_NUM}
          requires:
            - build_test
jobs:
  build_test:
    docker:
      - image: centos:centos7
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
           yum install make -y
           yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
           yum install docker -y
            make
